<?php

namespace Storm\Query\PostGreSql;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-30 at 04:38:38.
 */
class UpdateTest extends TestCase
{
  /**
   * @var QueryUpdate
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new Update;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers Storm\Query\PostGreSql\Update::getQuery
   */
  public function testGetQuery()
  {
    $actual = $this->object->getQuery();
		$this->assertEquals('UPDATE  SET  WHERE ;', $actual);
  }

  /**
   * @covers Storm\Query\PostGreSql\Update::set
   */
  public function testSet()
  {
    $instance = $this->object->set('foo', 'bar');
		$this->assertInstanceOf('Storm\Query\PostGreSql\Update', $instance);
  }
}
