<?php

namespace Storm\Query\PostGreSql;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-30 at 04:38:38.
 */
class Storm_Query_PostGreSql_Utility_Test extends TestCase
{
  /**
   * @var QueryUtility
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new Utility;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers Storm\Query\PostGreSql\Utility::dropTable
   */
  public function testDropTable()
  {
    $instance = $this->object->dropTable('foobar');
		$this->assertInstanceOf('Storm\Query\PostGreSql\Utility', $instance);
  }

  /**
   * @covers Storm\Query\PostGreSql\Utility::getQuery
   */
  public function testGetQuery()
  {
    $actual = $this->object->getQuery();
		$this->assertEquals(';', $actual);
  }

  /**
   * @covers Storm\Query\PostGreSql\Utility::renameTable
   */
  public function testRenameTable()
  {
    $instance = $this->object->renameTable('foo', 'bar');
		$this->assertInstanceOf('Storm\Query\PostGreSql\Utility', $instance);
  }

  /**
   * @covers Storm\Query\PostGreSql\Utility::setSchema
   */
  public function testSetSchema()
  {
    $instance = $this->object->setSchema('foobar');
		$this->assertInstanceOf('Storm\Query\PostGreSql\Utility', $instance);
  }

  /**
   * @covers Storm\Query\PostGreSql\Utility::truncate
   */
  public function testTruncate()
  {
    $instance = $this->object->truncate('foobar');
		$this->assertInstanceOf('Storm\Query\PostGreSql\Utility', $instance);
  }
}
