<?php

namespace Storm\Query\Sqlite;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:03.
 */
class Storm_Query_Sqlite_Create_Test extends TestCase
{
  /**
   * @var QueryCreate
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Create('foobar');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers Storm\Query\Sqlite\Create::__construct
   */
  public function test__construct()
  {
    $actual = $this->object->__construct('foobar');

    $this->assertNull($actual);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::addField
   */
  public function testAddField()
  {
    $instance = $this->object->addField('foobar', array());
    $this->assertInstanceOf('Storm\Query\Sqlite\Create', $instance);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::addForeignKey
   */
  public function testAddForeignKey()
  {
    $instance = $this->object->addForeignKey('foobar', 'foo', 'bar');
    $this->assertInstanceOf('Storm\Query\Sqlite\Create', $instance);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::addUniqueKey
   * @todo   Implement testAddUniqueKey().
   */
  public function testAddUniqueKey()
  {
    $instance = $this->object->addUniqueKey('foobar', array());
    $this->assertInstanceOf('Storm\Query\Sqlite\Create', $instance);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::getQuery
   */
  public function testGetQuery()
  {
    $this->object->addField('foobar', array(
      'type'    => 'varchar',
      'default'  => 'something',
      'null'    => true,
      'attribute'  => 'unsigned',
      'length'  => 255
    ));
    $this->object->addForeignKey('foobar', 'foo', 'bar');
    $this->object->addUniqueKey('foobar', array('foobar'));
    $this->object->setComments('foobar');
    $actual = $this->object->getQuery();
    $this->assertEquals('CREATE TABLE "foobar" ("foobar" varchar(255) '
    . 'unsigned DEFAULT NULL, UNIQUE "foobar" ("foobar"), FOREIGN KEY '
    . '"foobar" REFERENCES foo(bar));', $actual);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::setComments
   */
  public function testSetComments()
  {
    $instance = $this->object->setComments('foobar');
    $this->assertInstanceOf('Storm\Query\Sqlite\Create', $instance);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::setFields
   */
  public function testSetFields()
  {
    $instance = $this->object->setFields(array('foobar'));
    $this->assertInstanceOf('Storm\Query\Sqlite\Create', $instance);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::setForiegnKeys
   */
  public function testSetForiegnKeys()
  {
    $instance = $this->object->setForiegnKeys(array('foobar'));
    $this->assertInstanceOf('Storm\Query\Sqlite\Create', $instance);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::setTable
   */
  public function testSetTable()
  {
    $instance = $this->object->setTable('foobar');
    $this->assertInstanceOf('Storm\Query\Sqlite\Create', $instance);
  }

  /**
   * @covers Storm\Query\Sqlite\Create::setUniqueKeys
   */
  public function testSetUniqueKeys()
  {
    $instance = $this->object->setUniqueKeys(array('foobar'));
    $this->assertInstanceOf('Storm\Query\Sqlite\Create', $instance);
  }
}
