<?php

namespace Storm\Query;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Storm_Query_Update_Test extends TestCase
{
  /**
   * @var QueryUpdate
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new Update('foobar');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers Storm\Query\Update::getQuery
   */
  public function testGetQuery()
  {
    $actual = $this->object->getQuery();
		$this->assertEquals('UPDATE foobar SET ;', $actual);
  }

  /**
   * @covers Storm\Query\Update::set
   */
  public function testSet()
  {
    $instance = $this->object->set('foo', 'bar');
		$this->assertInstanceOf('Storm\Query\Update', $instance);
  }
}
